Insert into ROL (ROL_ID,DESCRIPCION,FECHA_CREACION,ESTADO) values (2,'proveedor',to_date('18-09-04','RR-MM-DD'),'ACTIVO');
Insert into ROL (ROL_ID,DESCRIPCION,FECHA_CREACION,ESTADO) values (1,'cliente',to_date('18-09-04','RR-MM-DD'),'ACTIVO');

Insert into CATEGORIA (CATEGORIA_ID,NOMBRE,DESCRIPCION,FECHA_CREACION,ESTADO) values (2,'Carpinteria','todo lo relacionado con madera',to_date('18-09-06','RR-MM-DD'),'ACTIVO');
Insert into CATEGORIA (CATEGORIA_ID,NOMBRE,DESCRIPCION,FECHA_CREACION,ESTADO) values (1,'Electricidad','todo lo relacionado con la electricidad',to_date('18-08-27','RR-MM-DD'),'ACTIVO');


Insert into USUARIO (USUARIO_ID,ROL_ID,COORDENADA_ID,USERNAME,PASSWORD,NOMBRES,APELLIDOS,CORREO,DIRECCION,TELEFONO,DESCRIPCION_PERFIL,FECHA_CREACION,ESTADO,IDENTIFICACION) values (1,1,5,'ramiro','12345','ramiro ','villaveces','rvillaveces4892@gmail.com','crr 74 # 37 sur - 24','3567945',null,to_date('18-09-05','RR-MM-DD'),'ACTIVO','1234567890');
Insert into USUARIO (USUARIO_ID,ROL_ID,COORDENADA_ID,USERNAME,PASSWORD,NOMBRES,APELLIDOS,CORREO,DIRECCION,TELEFONO,DESCRIPCION_PERFIL,FECHA_CREACION,ESTADO,IDENTIFICACION) values (3,2,4,'carlos','12345','Carlos','Herrera','cherrera@gmail.com','Cra. 74 #35c Sur-60 a 35c Sur-2','3256645','certificado en instalaciones electricas',to_date('18-09-05','RR-MM-DD'),'ACTIVO','1234567891');
Insert into USUARIO (USUARIO_ID,ROL_ID,COORDENADA_ID,USERNAME,PASSWORD,NOMBRES,APELLIDOS,CORREO,DIRECCION,TELEFONO,DESCRIPCION_PERFIL,FECHA_CREACION,ESTADO,IDENTIFICACION) values (4,2,6,'andres','12345','Andres','Garcia','agarcia@gmail.com','Cra. 11a #32 Sur-1 a 32 Sur-61','6616326','Hago mudanzas a donde sea',to_date('18-09-05','RR-MM-DD'),'ACTIVO','1234567892');


Insert into COORDENADAS (COORDENADA_ID,LATITUD,LONGITUD,FECHA_CREACION,ESTADO) values (4,'4,621233','-74,1486376',to_date('18-08-26','RR-MM-DD'),'ACTIVO');
Insert into COORDENADAS (COORDENADA_ID,LATITUD,LONGITUD,FECHA_CREACION,ESTADO) values (5,'4,619951','-74,149556',to_date('18-09-05','RR-MM-DD'),'ACTIVO');
Insert into COORDENADAS (COORDENADA_ID,LATITUD,LONGITUD,FECHA_CREACION,ESTADO) values (6,'4,569702','-74,103627',to_date('18-09-05','RR-MM-DD'),'ACTIVO');

Insert into SERVICIO (SERVICIO_ID,CATEGORIA_ID,DESCRIPCION,FECHA_CREACION,ESTADO) values (2,2,'Ebanisteria',to_date('18-09-06','RR-MM-DD'),'ACTIVO');
Insert into SERVICIO (SERVICIO_ID,CATEGORIA_ID,DESCRIPCION,FECHA_CREACION,ESTADO) values (3,2,'Muebles',to_date('18-09-06','RR-MM-DD'),'ACTIVO');
Insert into SERVICIO (SERVICIO_ID,CATEGORIA_ID,DESCRIPCION,FECHA_CREACION,ESTADO) values (1,1,'instalaciones electricas internas',to_date('18-08-27','RR-MM-DD'),'ACTIVO');
